package com.smartlib.ai.observability;

public enum AiErrorCategory {
    NONE,
    VALIDATION,
    AUTHENTICATION,
    AUTHORIZATION,
    RATE_LIMIT,
    PROVIDER,
    PROVIDER_AUTH,
    PROVIDER_RATE_LIMIT,
    PROVIDER_UNAVAILABLE,
    PROVIDER_TIMEOUT,
    PROVIDER_NOT_FOUND,
    TOOL,
    DATABASE,
    VECTOR_DB,
    WEB_GROUNDING,
    SECURITY,
    INTERNAL
}
