package com.smartlib.service;

import com.smartlib.dto.reservation.ReservationRequest;
import com.smartlib.dto.reservation.ReservationResponse;
import com.smartlib.entity.Book;
import com.smartlib.entity.Reservation;
import com.smartlib.entity.User;
import com.smartlib.enums.BookCopyStatus;
import com.smartlib.enums.BorrowStatus;
import com.smartlib.enums.ReservationStatus;
import com.smartlib.exception.BadRequestException;
import com.smartlib.exception.ResourceNotFoundException;
import com.smartlib.repository.BookCopyRepository;
import com.smartlib.repository.BookRepository;
import com.smartlib.repository.BorrowingRepository;
import com.smartlib.repository.ReservationRepository;
import lombok.RequiredArgsConstructor;

import org.springframework.security.core.Authentication;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;

@Service
@RequiredArgsConstructor
public class ReservationService {

    private final ReservationRepository reservationRepository;
    private final BookRepository bookRepository;
    private final BorrowingRepository borrowingRepository;
    private final BookCopyRepository bookCopyRepository;


    // ============================================================
    // CREATE RESERVATION
    // ============================================================

    @Transactional
    public ReservationResponse createReservation(
            ReservationRequest request,
            Authentication authentication) {

        User user = getCurrentUser(authentication);

        Book book =
                bookRepository
                        .findById(request.getBookId())
                        .orElseThrow(() ->
                                new ResourceNotFoundException(
                                        "Book not found"
                                ));


        // --------------------------------------------------------
        // Physical inventory is the source of truth.
        // --------------------------------------------------------

        long availableCopies =
                bookCopyRepository
                        .countByBookIdAndStatus(
                                book.getId(),
                                BookCopyStatus.AVAILABLE
                        );


        if (availableCopies > 0) {

            throw new BadRequestException(
                    "Book is currently available. You can borrow it instead."
            );
        }


        // --------------------------------------------------------
        // Already reserved?
        // --------------------------------------------------------

        boolean alreadyReserved =
                reservationRepository
                        .existsByUserIdAndBookIdAndStatusIn(
                                user.getId(),
                                book.getId(),
                                List.of(
                                        ReservationStatus.WAITING,
                                        ReservationStatus.READY
                                )
                        );

        if (alreadyReserved) {

            throw new BadRequestException(
                    "You already have an active reservation for this book."
            );
        }


        // --------------------------------------------------------
        // Already borrowing?
        // --------------------------------------------------------

        boolean alreadyBorrowed =
                borrowingRepository
                        .existsByUserIdAndBookIdAndStatus(
                                user.getId(),
                                book.getId(),
                                BorrowStatus.BORROWED
                        );

        if (alreadyBorrowed) {

            throw new BadRequestException(
                    "You already have this book borrowed."
            );
        }


        // --------------------------------------------------------
        // Create FIFO reservation.
        // reservedAt is automatically generated by entity.
        // --------------------------------------------------------

        Reservation reservation =
                Reservation.builder()
                        .user(user)
                        .book(book)
                        .status(
                                ReservationStatus.WAITING
                        )
                        .build();


        Reservation saved =
                reservationRepository.save(
                        reservation
                );


        return toResponse(saved);
    }


    // ============================================================
    // GET MY RESERVATIONS
    // ============================================================

    @Transactional(readOnly = true)
    public List<ReservationResponse> getMyReservations(
            Authentication authentication) {

        User user =
                getCurrentUser(authentication);

        return reservationRepository
                .findByUserId(user.getId())
                .stream()
                .map(this::toResponse)
                .toList();
    }


    // ============================================================
    // GET MY ACTIVE RESERVATIONS
    // ============================================================

    @Transactional(readOnly = true)
    public List<ReservationResponse> getMyActiveReservations(
            Authentication authentication) {

        User user =
                getCurrentUser(authentication);

        return reservationRepository
                .findByUserIdAndStatusIn(
                        user.getId(),
                        List.of(
                                ReservationStatus.WAITING,
                                ReservationStatus.READY
                        )
                )
                .stream()
                .map(this::toResponse)
                .toList();
    }


    // ============================================================
    // CANCEL RESERVATION
    // ============================================================

    @Transactional
    public ReservationResponse cancelReservation(
            Long reservationId,
            Authentication authentication) {

        User user =
                getCurrentUser(authentication);


        Reservation reservation =
                reservationRepository
                        .findById(reservationId)
                        .orElseThrow(() ->
                                new ResourceNotFoundException(
                                        "Reservation not found"
                                ));


        if (!reservation
                .getUser()
                .getId()
                .equals(user.getId())) {

            throw new BadRequestException(
                    "You cannot cancel another user's reservation."
            );
        }


        if (reservation.getStatus()
                == ReservationStatus.COMPLETED) {

            throw new BadRequestException(
                    "Completed reservations cannot be cancelled."
            );
        }


        if (reservation.getStatus()
                == ReservationStatus.CANCELLED) {

            throw new BadRequestException(
                    "Reservation is already cancelled."
            );
        }


        reservation.setStatus(
                ReservationStatus.CANCELLED
        );


        Reservation saved =
                reservationRepository.save(
                        reservation
                );


        /*
         * If a READY reservation is cancelled,
         * its RESERVED copy must be released.
         *
         * The current Reservation entity doesn't store
         * bookCopy_id, so this is intentionally handled
         * by the return/borrowing transaction for now.
         */

        return toResponse(saved);
    }


    // ============================================================
    // FIND OLDEST WAITING RESERVATION
    // ============================================================

    @Transactional
    public Reservation findOldestWaitingReservation(
            Long bookId) {

        return reservationRepository
                .findOldestWaitingForUpdate(bookId)
                .orElse(null);
    }


    // ============================================================
    // MARK RESERVATION READY
    // ============================================================

    @Transactional
    public Reservation markReady(
            Reservation reservation) {

        reservation.setStatus(
                ReservationStatus.READY
        );

        reservation.setReadyAt(
                LocalDateTime.now()
        );

        return reservationRepository.save(
                reservation
        );
    }


    // ============================================================
    // COMPLETE RESERVATION
    // ============================================================

    @Transactional
    public Reservation completeReservation(
            Reservation reservation) {

        reservation.setStatus(
                ReservationStatus.COMPLETED
        );

        return reservationRepository.save(
                reservation
        );
    }


    // ============================================================
    // CURRENT USER
    // ============================================================

    private User getCurrentUser(
            Authentication authentication) {

        if (authentication == null
                || authentication.getPrincipal() == null) {

            throw new BadRequestException(
                    "Authentication is required."
            );
        }

        return (User) authentication.getPrincipal();
    }


    // ============================================================
    // RESPONSE
    // ============================================================

    private ReservationResponse toResponse(
            Reservation reservation) {

        return ReservationResponse.builder()

                .id(
                        reservation.getId()
                )

                .bookId(
                        reservation
                                .getBook()
                                .getId()
                )

                .bookTitle(
                        reservation
                                .getBook()
                                .getTitle()
                )

                .userId(
                        reservation
                                .getUser()
                                .getId()
                )

                .userName(
                        reservation
                                .getUser()
                                .getName()
                )

                .status(
                        reservation
                                .getStatus()
                                .name()
                )

                .reservedAt(
                        reservation
                                .getReservedAt()
                )

                .readyAt(
                        reservation
                                .getReadyAt()
                )

                .build();
    }
}